---
- hosts: ubuntu
  gather_facts: no

  tasks:
    - name: Register the output of the 'uptime' command
      command: uptime
      register: system_uptime

    - name: Print output of the 'uptime' command
      debug:
        var: system_uptime.stdout

    - name: Print a message if a command resulted in a change.
      debug:
        msg:
      when: system_uptime is changed