---
- name: Converge
  hosts: ubuntu

  tasks:
    - name: Update apt cache (on debian)
      apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

- import_playbook: ../../main.yml

