- hosts: web1
  tasks:

  - name: Install httpd
    yum: 
     name: httpd
     state: latest

  - name: Start httpd
    systemd:
     name: httpd
     enabled: yes

  - name: Install wget
    yum:
     name: wget
     state: latest

  - name: Install unzip
    yum: 
      name: unzip
      state: latest 

  
  - name: Download template
    get_url: 
     url: https://www.free-css.com/assets/files/free-css-templates/download/page273/corso.zip
     dest: /tmp/

  
  - name: Extract corso.zip into /var/www/html
    unarchive: 
      src: /tmp/corso.zip
      dest: /var/www/html
      remote_src: yes 