---
- name: Ensure Apache is installed
  package:
    name: apache2
    state: present
  register: foo
- debug: var=foo['failed']  #var=foo.failed 

- name: Add an environment variable to the remote user's shell
  lineinfile:
    path: "/home/ubuntu/.bashrc"
    regexp: '^ENV_VAR='
    line: 'ENV_VAR=value'
  become: false

- name: Source the bashrc file to get the updated environment variable
  shell: |
    source /home/ubuntu/.bashrc
    echo $ENV_VAR
  args:
    executable: /bin/bash
  register: env_var_value
  become_user: ubuntu

- debug: 
    msg: "The environment variable value is {{ env_var_value.stdout }}"

- name: Ensure the Apache configuration directory exists
  file:
    path: /etc/apache2/sites-available
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy test config file
  copy:
    src: files/test.conf
    dest: /etc/apache2/sites-available/test.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache

- name: Make sure handlers are flushed immediately
  meta: flush_handlers

- name: Ensure Apache is running and starts at boot
  systemd:
    name: apache2
    state: started
    enabled: true